Ensembl/ensembl-hive

modules/Bio/EnsEMBL/Hive/Meadow.pm, modules/Bio/EnsEMBL/Hive/Meadow/LOCAL.pm, modules/Bio/EnsEMBL/Hive/Meadow/LSF.pm, modules/Bio/EnsEMBL/Hive/Queen.pm, modules/Bio/EnsEMBL/Hive/Scheduler.pm, modules/Bio/EnsEMBL/Hive/Valley.pm, t/04.meadow/lsf.t, t/04.meadow/valley.t
This fixes @danstaines's issue:
[Feb 11th at 09:49]
I've got a problem with hive where I supply a registry, and the registry takes a couple of minutes to load (this is normal with 40k bacteria unfortunately).
The registry takes a lot of time to load, so the worker is running from the LSF point-of-view but is not registered in the database yet (because the DBAdaptor object is not ready yet). Because of the discrepancy, beekeeper thinks that nothing is running and keep on submitting new workers (beyond the analysis capacity)
My fix is to basically count those workers as _pending_. Because the Valley/Meadow had a method to get the running workers and another one to get the pending workers, I had to unify them into a single method that takes the list of the workers that have registered and …
=> Fix for DS slow registry

modules/Bio/EnsEMBL/Hive/DBSQL/SqlSchemaAdaptor.pm
Previously backtick ls command was used to fetch the list of sql patches filenames.
By using backtick it is required to fork a new process. This would potentially be
a problem for a running process that uses large amount of memory. If there is not
enough spare memory left in the system, the fork operation could be aborted because
of "cannot allocate memory" error.
Fixes ENSEMBL-4823.
=> Use File::Glob to get the list of filenames

modules/Bio/EnsEMBL/Hive/Process.pm, modules/Bio/EnsEMBL/Hive/RunnableDB/SystemCmd.pm, modules/Bio/EnsEMBL/Hive/Utils.pm, modules/Bio/EnsEMBL/Hive/Utils/Test.pm, t/05.runnabledb/systemcmd.t
I've added a few options in `Process::run_system_command` and `RunnaleDB::SystemCmd` to:
- add a time limit (mimicking LSF's _RUNLIMIT_)
- capture the standard output
- record how long the command took
=> More options when running system commands

modules/Bio/EnsEMBL/Hive/AnalysisJob.pm, t/02.api/local_dataflows.t
This is a request for comments. I've tried to compile a list of all possible `dataflow_output_id` calls, with the expected behaviour from Hive. At the moment, the test doesn't pass on 2.4 (neither it does on master), but I've got a couple of commits ready, assuming these below are the expected outcomes.
There is a case where I really don't know what's more "natural". If the template needs `a_multiplier` and `a_multiplier` is set to 9650156169 in the input_id, but to 27 in the parameter hash (the parameter has been modified at runtime). Which value should be used in the dataflow ??
=> New unit-test for dataflow_output_id under various conditions

.travis.yml, cpanfile, modules/Bio/EnsEMBL/Hive/RunnableDB/NotifyByEmail.pm, t/05.runnabledb/email.t
Addresses two comments that are only 2 years old ^^:
- https://genomes-ebi.slack.com/archives/C0HTNH2GG/p1456929232000231
- https://genomes-ebi.slack.com/archives/C0HTNH2GG/p1456929816000233
The NotifyByEmail Runnable was really simplistic. Switching to [Email::Stuffer](http://search.cpan.org/~rjbs/Email-Stuffer-0.014/lib/Email/Stuffer.pm) allows adding attachments very easily, and gives a better support of multi-part emails, e.g. with HTML content, etc. Note for @james-monkeyshines : Email::Stuffer is in fact just a wrapper around Email::MIME, which you are now using in EGPipeline/RNAFeatures/EmailRNAReport.pm instead of MIME::Lite, so I expect it to work in your pipelines.
MIME::Lite is not maintained any more (http://search.cpan.org/~rjbs/MIME-Lite-3.030/lib/MIME/Lite.pm) but since it …
=> Improvements to NotifyByEmail

docs/advanced_usage/mpi.rst, docs/creating_runnables/runnable_api.rst, modules/Bio/EnsEMBL/Hive/GuestProcess.pm, modules/Bio/EnsEMBL/Hive/Meadow/LOCAL.pm, modules/Bio/EnsEMBL/Hive/Meadow/LSF.pm, modules/Bio/EnsEMBL/Hive/Process.pm, modules/Bio/EnsEMBL/Hive/Queen.pm, modules/Bio/EnsEMBL/Hive/RunnableDB/DatabaseDumper.pm, modules/Bio/EnsEMBL/Hive/RunnableDB/Dummy.pm, modules/Bio/EnsEMBL/Hive/RunnableDB/JobFactory.pm, modules/Bio/EnsEMBL/Hive/RunnableDB/SqlCmd.pm, modules/Bio/EnsEMBL/Hive/RunnableDB/SqlHealthcheck.pm, modules/Bio/EnsEMBL/Hive/Valley.pm, modules/Bio/EnsEMBL/Hive/Worker.pm, scripts/beekeeper.pl, t/02.api/latest_schema_patch.t, t/04.meadow/meadow-longmult.mt, t/10.pipeconfig/gc_dataflow.t, t/10.pipeconfig/gcpct.t, t/10.pipeconfig/guest_language.t, t/10.pipeconfig/kmer.t, t/10.pipeconfig/longmult.t
As I was writing the documentation of the Runnable API, I realized that `Process::say_with_header` was printing messages to either stdout or stderr, depending whether the job is standalone or not. I wanted to harmonize that, and ended up fixing up several other modules. My guidelines were:
- Use `say_with_header` in Runnables
- Print to stdout (no STDERR/warn) when the message is just an information (I kept all the "real" warnings as `warn`)
=> Consistently print messages to stdout

modules/Bio/EnsEMBL/Hive/Process.pm
eHive provides `$self->data_dbc` to Runnables, which defaults to the current (eHive) database but can be overridden with the `db_conn` parameter. In standaloneJob mode, since there is no database, `db_conn` is (meant to be) the only way of setting this, and this commit prints a clearer error message (with the stack trace) when the parameter is missing
```
Running 'Bio::EnsEMBL::Hive::RunnableDB::SqlHealthcheck' with input_id='{"query" => "SELECT * FROM meta"}' :
Standalone worker 8333 : WORKER_ERROR : In standaloneJob mode, $self->data_dbc requires the -db_conn parameter to be defined on the command-line at /home/matthieu/workspace/src/hive/master/modules/Bio/EnsEMBL/Hive/Process.pm line 613.
Bio::EnsEMBL::Hive::Process::throw() called at …
```
=> Print a nicer error message if $self->data_dbc cannot be evaluated

modules/Bio/EnsEMBL/Hive/DBSQL/DBConnection.pm, modules/Bio/EnsEMBL/Hive/Scripts/InitPipeline.pm, scripts/beekeeper.pl, scripts/hoover_pipeline.pl, scripts/load_resource_usage.pl, scripts/runWorker.pl, scripts/seed_pipeline.pl, scripts/tweak_pipeline.pl
beekeeper.pl, like other scripts needs a read+write connection to the database.
As I often (by mistake) use `ensro`, I'm a bit tired of seeing this stack trace:
```
mattxps:~ $ beekeeper.pl -url 'mysql://ensro@localhost/matthieu_test_db_master'
Pipeline name: long_mult
Default meadow: LOCAL/mattxps
DBD::mysql::st execute failed: INSERT command denied to user 'ensro'@'localhost' for table 'beekeeper' at /home/matthieu/workspace/src/hive/master/modules/Bio/EnsEMBL/Hive/DBSQL/StatementHandle.pm line 119.
DBD::mysql::st execute failed: INSERT command denied to user 'ensro'@'localhost' for table 'beekeeper' at /home/matthieu/workspace/src/hive/master/modules/Bio/EnsEMBL/Hive/DBSQL/StatementHandle.pm line 119.
at /home/matthieu/workspace/src/hive/master/modules/Bio/EnsEMBL/Hive/DBSQL/StatementHa …
```
=> Show a nice error message when connecting to the database with a read-only user

modules/Bio/EnsEMBL/Hive/DBSQL/DBAdaptor.pm, modules/Bio/EnsEMBL/Hive/DataflowRule.pm, modules/Bio/EnsEMBL/Hive/HivePipeline.pm, modules/Bio/EnsEMBL/Hive/PipeConfig/HiveGeneric_conf.pm, modules/Bio/EnsEMBL/Hive/Storable.pm, modules/Bio/EnsEMBL/Hive/Utils/PCL.pm
My test is Compara's Protein-Tree pipeline. With the proposed changes, loading the PipeConfig file (`$pipeconfig_object->add_objects_from_config($pipeline)`) now takes 0.7 seconds instead of 16 seconds.
The main improvements come from:
- storing new subs in AUTOLOAD: 16 seconds -> 4 seconds
- caching `DataflowRule::unitargets`: 4 seconds -> 0.7 seconds
There are other minor improvements:
- only stringifying the objects in verbose mode
- keep the list of Dataflow targets locally instead of searching them in the collection
=> Performance improvements to init_pipeline.pl/generate_graph.pl

docker/Dockerfile
It makes the docker image bigger though: 1.1GB instead of 666MB
=> Add java to the docker image so that the Java wrapper works out of the box

modules/Bio/EnsEMBL/Hive/AnalysisStats.pm, modules/Bio/EnsEMBL/Hive/DBSQL/AnalysisJobAdaptor.pm, modules/Bio/EnsEMBL/Hive/DBSQL/RoleAdaptor.pm, modules/Bio/EnsEMBL/Hive/Queen.pm
rather than hard-coding them everywhere
This makes adding/removing statuses easier (e.g. when we get job attempts) but also guarantees all those various methods are kept in sync
=> List the job statuses an their purpose only once

modules/Bio/EnsEMBL/Hive/Utils/URL.pm
This allows using the Perl debugger without having to set EHIVE_SANITIZED_ARGS=1
=> bugfix: avoid calling exec whilst in the Perl debugger not to confuse the latter

modules/Bio/EnsEMBL/Hive/DBSQL/DBConnection.pm, t/01.utils/redirect_stack.t, t/02.api/fetch_and_count_by_multiple_columns.t, t/02.api/naked_table_adaptor.t, t/10.pipeconfig/longmult.t
Whilst looking into the Travis errors for 2.4, I've found that `chdir` does *not* return the current directory ! I've unfortunately assumed this in all the tests :( There will certainly be more tests to fix on the other branches, but I'll do that together with the merge.
Also, since v1.9 is only compatible with the Ensembl Core API up to version 73, I am now checking the version number in the code itself to print a clear error message.
=> Various fixes: chdir and Core API

scripts/travis_run_tests.sh, wrappers/python3/eHive/Params.py, wrappers/python3/eHive/Process.py
This fixes another issue I've found with @marcoooo yesterday. `self.param_required('a')` is supposed to raise an exception if `a` is _None_ (like in Perl). In fact, when the behaviour of the param* methods was rationalised in Perl, the decisions should have been applied to the Python implementation, but I forgot to do so.
Both implementations should now be consistent and in sync with the manual: https://ensembl-hive.readthedocs.io/en/master/creating_runnables/IO_and_errors.html#parameter-handling
=>  Fixed the Params API in Python

modules/Bio/EnsEMBL/Hive/Queen.pm, modules/Bio/EnsEMBL/Hive/Scheduler.pm
I found those when reviewing the changes I've made around the scheduler. Technically there is only 1 bug, so the other commits probably should be put on master instead.
Changes are about sync-ing an analysis, or waiting for the sync to complete (when being performed by another agent). I think there are a few cases where we don't need to sync again, and a case where we need to report that the sync failed.
The Scheduler can also be simplified and use `safe_synchronize_AnalysisStats`.
=> Various fixes related to analysis sync-ing

modules/Bio/EnsEMBL/Hive/DBSQL/DBConnection.pm
When initialising a pipeline `has_write_access` errors as my user doesn't have `select` privileges on the `mysql.user` table.
SELECT command denied to user 'kiwiroy'@'hostname.co.nz' for table 'user'
**Edit** The [# TODO](https://github.com/Ensembl/ensembl-hive/blob/c1c364dfd79a1f3375889bf4d11919aaf53db68a/modules/Bio/EnsEMBL/Hive/DBSQL/DBConnection.pm#L386) is attended to in e7f5881.
=> use information schema

.travis.yml, scripts/dev/travis_run_tests.sh
While the decrease in the time taken to test on travis ([before](https://travis-ci.org/kiwiroy/ensembl-hive/builds/447572596) vs [after](https://travis-ci.org/kiwiroy/ensembl-hive/builds/447600045)) isn't as significant as I hoped there is definitely a benefit that the log files are shorter. The ~11 year old 5.10 still dominates the time taken for the integration suite.
=> Cache CPAN dependencies for faster builds

docs/dev/development_guidelines.rst, modules/Bio/EnsEMBL/Hive/DBSQL/BaseAdaptor.pm, modules/Bio/EnsEMBL/Hive/DBSQL/CoreDBConnection.pm, modules/Bio/EnsEMBL/Hive/DBSQL/DBConnection.pm, modules/Bio/EnsEMBL/Hive/DBSQL/StatementHandle.pm, modules/Bio/EnsEMBL/Hive/RunnableDB/DatabaseDumper.pm, modules/Bio/EnsEMBL/Hive/RunnableDB/MySQLTransfer.pm, modules/Bio/EnsEMBL/Hive/RunnableDB/SqlCmd.pm, scripts/dev/sql2rst.pl, scripts/generate_timeline.pl, t/02.api/drop_hive_tables.t, t/02.api/latest_schema_patch.t, t/02.api/reconnect.t
The issue was raised by @MatBarba . In ENSCORESW-2913 he managed to identify that a Python Runnable that just sleeps would raise the following error after 30 min:
```
DBD::mysql::db primary_key failed: MySQL server has gone away at (...)/modules/Bio/EnsEMBL/Hive/DBSQL/BaseAdaptor.pm line 244, <$CHILD_RDR> line 6.
```
30 min is indeed the timeout parameter of the server he was using.
The `primary_key` "dbh" method (and a few others) were indeed called on database handles without checking if the handle is still valid, and without any `eval {}` protection, even though such protection is available via the `AUTOLOAD` in `DBSQL::DBConnection`. The fix is to move those calls from the database handle to the database connection (new "best practice").
`prepare` is slightly more tricky to fix since …
=> Protect db_handle methods against "MySQL server has gone away"

modules/Bio/EnsEMBL/Hive/Utils/Collection.pm, t/01.utils/collection.t
This is a follow up to https://github.com/Ensembl/ensembl-hive/pull/61.
It relates to https://www.ebi.ac.uk/panda/jira/browse/ENSCORESW-2558 but the scope has increased to any field and not just Analysis tags.
A new `~` search operator is introduced, that allow regex searches on named fields.
It extends the Analyses pattern syntax with `expression = <word> '~' <any>` where any can be a regex (contain `%`).
=> Collection field regex search

sql/patch_2019-01-24.mysql, sql/patch_2019-01-24.pgsql, sql/patch_2019-01-24.sqlite, sql/procedures.mysql, sql/procedures.pgsql, sql/procedures.sqlite
This PR won't pass as the changes should be accompanied with SQL patches, but I wanted you to have a look at it first. If you have any suggestions about the views, or feedback from people, it'd be great to bundle all the changes.
For instance, I renamed `count(*)` to `num_workers` but I've now realised that a similar column in `resource_usage_stats` is called `workers`, whereas in `progress` it's just `cnt`
Matthieu
=> Minor improvement to the resource usage view

modules/Bio/EnsEMBL/Hive/Meadow/LOCAL.pm
This is an alternative to #68.
Instead of having to list every module that runs `exec` like this:
```
exec { $args[0] } @args;
```
I've just tried changing the scope of the override and it works on my laptop. Let's give it a try on Travis and the farm !
=>  Workaround for IPC::Run compilation failure at pipeline initialisation time

modules/Bio/EnsEMBL/Hive/Beekeeper.pm, modules/Bio/EnsEMBL/Hive/DBSQL/BeekeeperAdaptor.pm, modules/Bio/EnsEMBL/Hive/Meadow/LOCAL.pm, modules/Bio/EnsEMBL/Hive/Meadow/LSF.pm, modules/Bio/EnsEMBL/Hive/Queen.pm, scripts/beekeeper.pl, t/03.scripts/beekeeper_big_red_button.t
Block all active Beekeepers, attempt to kill all active workers, report on both. This can fail to shut everything down because the current beekeeper might not be able to reach certain meadows (_e.g._ LOCAL on a different host) or have insufficient permissions to kill certain workers (_e.g._ processes or batch jobs belonging to a different user) but it seems to be all we could do without actively communicating with other Beekeepers and it's better than nothing.
=> Add a beekeeper option for attempting to stop the whole pipeline

modules/Bio/EnsEMBL/Hive/Utils/Test.pm
This is to help understanding the TAP output for standalone jobs that don't emit all the events they are supposed to emit. It will now stringify and print the missing ones
=> Better diagnostic: tell what events were expected

modules/Bio/EnsEMBL/Hive/HivePipeline.pm
Here are two bugs that I've identified whilst reviewing #62 
1. The tweak query printed back to the user was showing the string `meadow` instead of the actual meadow type.
2. The script allowed deleting non-existing pipeline-wide parameters, which was resulting in Perl warnings about undefined values etc
1. Print the variable `$meadow_type` instead
2. This had been fixed on 2.5 but not backported. I simply cherry-picked the commit
Once this is accepted and merged on the later branches, @mira13 will have to rebase her changes (#62) which may conflict. But it will make her changeset clearer.
No, there are currently no tests for tweak_pipeline.pl
N/A
_Have you run the entire test suite and no …
=> Misc. bugfixes in tweak_pipeline.pl

.readthedocs.yml
From time to time readthedocs.io changes the build container (and underlying Ubuntu version) that it uses to build documentation. When the Ubuntu version of the container changes, it breaks our documentation build, because our build relies on several external dependencies. These dependencies are satisfied by downloading and extracting specific .deb packages (specified in docs/rtd_upgrade.sh) which are specific to a specific Ubuntu version. By specifying a specific build container version, we can minimize the frequency of build-breaking upgrades, and easily update the specific .deb packages in rtd_upgrade.sh if needed.
Add .readthedocs.yml configuration file that specifies that rtd use the "stable" build container image.
This file will need to be maintained. In case of conflicts between …
=> [ENSCORESW-3082, ENSCORESW-3080] Add .readthedocs.yml config file specifying stable build image

.readthedocs.yml, docs/xhive/__init__.py, docs/xhive/analysis_diagram.py, docs/xhive/code_doc.py
See ENSCORESW-3081: Read the Docs is now actively pushing towards using Python3 for documentation building, the custom modules we use in the process are Python2-specific, and we would like to make the switch before RtD drop Python2 support - which is likely to happen sooner rather than later because Python2.7 reaches end of life in 2020.
Adapt Python2-specific code in our custom documentation-building modules so that it works with both Python2 and Python3. This is done in a Python3-centric way in order to minimise the effort of dropping Python2 support once we have decided to do so.
Slight overhead incurred by cross-version compatibility code. Temporary files are no longer opened in binary mode so there is a risk of the code no longer working as expected under Windows, assuming it has …
=> docs/xhive: support both python2 and python3

docs/dev/build_the_docs.rst
The links previously used here were, in spite of having .txt at the end, to respective GitHub HTML pages, which could come as a surprise to someone who saved the links directly from the ReadTheDocs page and then tried to feed the resulting files - with names still ending in .txt - to
pip. Using direct links both is less confusing and saves one click each, regardless of whether one downloads the files or just passes links directly to 'pip -r'.
Replaced old requirements.txt links in _docs/dev/build_the_docs.rst_ to ones pointing directly to raw content.
None I can think of.
no
N/A
I have rebuilt HTML documentation. Everything parses …
=> docs/dev/build_the_docs: use direct links to requirements.txt

docs/quickstart/install.rst, scripts/dev/travis_run_tests.sh
I have noticed that the Travis builds were strangely quick, as if Devel::Cover was not enabled. Indeed, it was still attached to Perl 5.10 !
Then I've found another document that was still referencing to 5.10
I've changed the version in both places.
Slower Travis build times on 5.14, but at least we get code coverage statistics
N/A
N/A
N/A
=> More Perl version upgrades

modules/Bio/EnsEMBL/Hive/DBSQL/CoreDBConnection.pm, modules/Bio/EnsEMBL/Hive/DBSQL/StatementHandle.pm
Seeing I need to add the message in two places, I'm wondering if I should introduce a new method, say in DBConnection, that tells whether an error message is due to lost connection, and call it from these two places. I could then add two other methods to tell whether an error message is (1) due to deadlock, (2) due to the unavailability of the server. Both are currently implemented the same way: `if $@ =~ /.../ or ...`
=> Catch another error message related to lost connection

modules/Bio/EnsEMBL/Hive/DBSQL/CoreDBConnection.pm, modules/Bio/EnsEMBL/Hive/DBSQL/DBConnection.pm, modules/Bio/EnsEMBL/Hive/DBSQL/StatementHandle.pm, modules/Bio/EnsEMBL/Hive/Utils/SQLErrorParser.pm
This is a follow-up of #73 . Several modules check the SQL error to reconnect, restart the transaction, etc, and sometimes several modules share the exact same piece of code.
I have created a new module that catalogues the various error messages known to each driver. Consumers (usually *DBConnection and StatementHandle) can then use helper functions to detect whether the message is of a certain error or not
None I can think ok
No, there are already some tests for that
N/A
Yes
=> Shared module to detect the SQL errors

modules/Bio/EnsEMBL/Hive/HivePipeline.pm
When setting control-flow rules (`wait_for`) with tweak_pipeline, unlike for other fields, there is no message stating that / which rules have been added:
```
$ tweak_pipeline.pl -url $(mysql-ens-compara-prod-6-ensadmin details url muffato_test_plants_goc_96) -tweak 'analysis[2].wait_for=ppp'
Tweak.Request   analysis[2].wait_for=ppp
Tweak.Found     1 analyses matching the pattern '2'
Tweak.Deleting  AnalysisCtrlRule: bbb ---| backbone_fire_clustering --> (missing value)
```
This gives the wrong impression that nothing has been added.
With this commit, the new rules are now listed:
```
$ tweak_pipeline.pl -url $(mysql-ens-compara-prod-6-ensadmin details url muffato_test_plants_goc_96) -tweak 'analysis[2].wait_for=qqq'
Tweak.Request   analysis[2].wait_for=qqq
Tweak.Found     1 analyses …
```
=> bugfix: add the missing print statements for tweaks that add control-flow rules

docs/conf.py
The Sphinx extension _sphinx.ext.pngmath_ is deprecated, which presumably means it will disappear at some point. There seem to be only two places in eHive documentation which rely on this yet we do use it.
_sphinx.ext.imgmath_ is a drop-in replacement for it _sphinx.ext.pngmath_ (its default output format is PNG and under the bonnet both use dvipng) so all this PR does is update the Sphinx configuration file to use the former. Now not only do we no longer get the deprecation warning but could now easily switch to SVG output by passing '-D imgmath_image_format=svg' to _sphinx-build_.
Sphinx versions older than 1.4 will no longer be supported. Mind you, 1.4 just under 3 years old now and our requirements file already demands 1.6.5. …
=> Have Sphinx use sphinx.ext.imgmath instead of sphinx.ext.pngmath

modules/Bio/EnsEMBL/Hive/Queen.pm, t/03.scripts/beekeeper_reset.t
I had missed this occurrence when I introduced the variable in 1d3cab12016a667263827192cc8249e56eedfb7d
The goal was to minimize the number of places with an hardcoded list of statuses so that most of the code will still work if somehow the list is changed
Import the module and use the variable
None I can think of
No, there is currently no test for `runWorker.pl --job_id`. Should I add one ? I can maybe add this to `t/03.scripts/beekeeper_reset.t`:
1. Try running a worker on the job_id of a READY job. It should return 0 and the job will be DONE
2. Try running a worker on the same job_id. It should return !=0 because the job is DONE. `when_completed` should not change
3. Try running a worker on the same job_id but with `--force`. It …
=> For maintainability use the list of statuses defined in AnalysisJobAdaptor

modules/Bio/EnsEMBL/Hive/Queen.pm
I've found this whilst working on a fix for negative job counts. `$self->` is missing here, which makes this line a _function_ call, not a _method_ call. The subroutine then gets `$stats` in `$self` and the other arguments (it expects `$stats` and `$has_refresh_just_been_done`) are both undefined.
Because it can deal with undefined `$stats` and returns immediately, it's never raised an error, but this means this call was doing nothing.
I guess this only means that failures were not reported with the freshest stats, which people may not even notice.
None
No
N/A
Yes. OK
=> bugfix: without $self this is a function call, not a method call

modules/Bio/EnsEMBL/Hive/Meadow.pm
Bugfix ;   If user configured RunWorkerPath to be empty string in hive_config.json
the runWorker script got erroneously prefixed with "/runWorker.pl"; 
According to the REMARKS in hive_config.json runWorker.pl is in PATH when set to empty string - so prefix with "/runWorker.pl" breaks code
N/A
- No unit test in code base for runWorker_path() 
Yes
=> Bugfix: RunWorkerPath erroneously prefixed with "/" if set to empty string

modules/Bio/EnsEMBL/Hive/Utils.pm
_Describe the problem. Please provide an example representing the motivation behind the need for having these changes in place._
This is from the Perl documentation:
> ```$Data::Dumper::Sparseseen or  $OBJ->Sparseseen([NEWVAL])```
>
> By default, Data::Dumper builds up the "seen" hash of scalars that it has encountered during serialization. This is very expensive.  This seen hash is necessary to support and even just detect circular references. It is exposed to the user via the "Seen()" call both for writing and reading.
>
> If you, as a user, do not need explicit access to the "seen" hash, then you can set the "Sparseseen" option to allow Data::Dumper to eschew building the "seen" hash for scalars that are known not to possess more than one reference. This speeds up serialization …
=> Makes Dumper (and stringify) faster

docker/Dockerfile
Docker builds have broken recently, because `apt` can't install the Oracle's Java version. See https://cloud.docker.com/u/ensemblorg/repository/registry-1.docker.io/ensemblorg/ensembl-hive/builds/6ade0715-5644-474d-8799-e157bdbac273
I've simply moved to openjdk. I can't remember why we needed oracle's version in the first place.
If anything requires Oracle specifically, but @mira13 is also leaning towards openjdk in #104 
I have rebuilt the Docker image locally and ran the example Java pipeline with ```prove -v /repo/ensembl-hive/t/10.pipeconfig/guest_language.t```
It worked
Yes (within the Docker image)
=> bugfix: oracle-java8 is not available any more, but openjdk-8 works

modules/Bio/EnsEMBL/Hive/HivePipeline.pm
I found several warnings about performing an addition on unitialized values when running the test suite locally.
The warnings come from `apply_tweaks`. The method assumes that all analyses have a dbID, which is forced into a numeric with `+ 0`. However, `init_pipeline.pl` applies the tweaks before storing the objects, so dbID is still undefined at this stage.
None
No
Yes: OK
=> bugfix: unstored objects don't have a dbID, so this raises a warning

wrappers/java/pom.xml
Version 2.6.1 of jackson-databind suffers from 5 high-severity and 1 moderate-severity security vulnerabilities. Use the first version known to fix all of these vulnerabilities.
Incidentally, all but one of these vulnerabilities date back to 2018 and earlier so one can't help but wonder why, seeing as this file was only introduced mid-May 2019, we used such an old and buggy version in the first place.
Come to think of it, why use fixed versions of Java dependencies rather than ranges?
Bump the version number of jackson-databind, one of the dependencies of the eHive Java wrapper, to 2.9.9 in order to address security vulnerabilities in 2.6.1.
jackson-databind-2.9.9 may be incompatible with out code base. I haven't seen anything suggesting that it might in its release docs, that said I …
=> wrappers/java/pom.xml: bump jackson-databind to 2.9.9

modules/Bio/EnsEMBL/Hive/Scripts/InitPipeline.pm
When initializing a pipeline with tweaks we currently see this:
```
$ init_pipeline.pl Bio::EnsEMBL::Hive::Examples::LongMult::PipeConfig::LongMultSt_javaconf $(mysql-local details hive) -tweak 'pipeline.param[take_time]=0'
(...)
> Applying tweaks.
ARRAY(0x2759b18)
> Storing the pipeline in the database.
(...)
```
1. We should be printing the actual tweaks, not a reference to a Perl array
2. The tweaks should only be displayed when `hive_debug_init` is set
The commits fix these two issues. Also, init_pipeline is now aware that the tweaks already contain `\n`, so no need to add it again.
N/A
No. The init_pipeline output is not covered by tests
Yes - OK
=> Tweak report during init_pipeline.pl

.travis.yml
From Xenial onwards services such as MySQL or PostgreSQL have to be explicitly enabled in .travis.yml. Due to issues with the availability of Perl versions we need we will stick with Trusty for the time being in spite of it being deprecated (see #112), then again it doesn't hurt to get this taken care of already.
Explicitly enable the services: mysql and postgresql in Travis builds.
None I can think of, enabling these services for Trusty is harmless.
No.
N/A
The change pertains specifically to Travis so running the test suite by hand doesn't help, have to wait for Travis builds on the head branch to finish.
=> Explicitly enable database services for Travis builds

modules/Bio/EnsEMBL/Hive/Scripts/PeekJob.pm, modules/Bio/EnsEMBL/Hive/Utils/Test.pm, scripts/peekJob.pl, t/03.scripts/peekJob_output.t
peekJob.pl allows us to check which params a given job has access to
Sometimes, we need to see which parameters a job has access to during development or testing. This is currently only possible by running runWorker.pl in debug mode and killing the job before it performs any other tasks.
Utilising the method that runWorker.pl itself uses to fetch params, this script has been implemented following the general structure of the e-hive codebase (with a module for the main functionality and a script to pass the parameters)
This script does not reveal any information about the source of the parameters, only their presence
Added new unit test to check the output of the script
=> New script to peek at job parameters

.travis.yml, docker/Dockerfile, docker/setup_cpan.Ubuntu-16.04.sh, docs/quickstart/install.rst
The 2.5 Docker image cannot run the Java wrapper since it doesn't have maven/openjdk installed.
Various commits, related to the Docker image and the JDK version:
- use OpenJDK 12 as it is the only released version that has the necessary dependencies (on both Travis and Docker)
- minor cleanup of the Docker image
By the way, if you have written any update to the doc / install guide for OpenJDK, can you add it to this branch ? If not, I will add something now
N/A
Not needed
Yes. OK
=> JDK version

modules/Bio/EnsEMBL/Hive/PipeConfig/HiveGeneric_conf.pm
Since 2.5, the commands being run are by default hidden (they can be shown with the `-hive_debug_init 1` flag), so if something goes wrong, you can only see the error message, not the command that caused the error.
When the command fails, print it too, alongside the error message.
N/A
N/A
=> Report the command that is failing

.codecov.yml
I've always found it very annoying that codecov complains about meaningless decreases of the coverage, like `80.88% (-0.04%) compared to e2e90e5 `. Coveralls has been configured to not report small differences but I couldn't find how to configure this in codecov ... until today :)
Do not complain about small decreases of the coverage
Does anyone need such precision and fine-grain decision in the codecov report ?
N/A, but I have checked that the yaml file is valid with
```
curl --data-binary @.codecov.yml https://codecov.io/validate
```
N/A
=> [codecov] Only report a failure when the coverage decreases by more than 1%

modules/Bio/EnsEMBL/Hive/PipeConfig/HiveGeneric_conf.pm
Jorge found this one by accident. He had put a `/` in the `pipeline_name` option and then generate_graph.pl failed with this error
```Error: <stdin>: syntax error in line 119 near '/'```
When doing my own tests, I realized that the URLs themselves would be confusing with a `/` in the database name, so better to remove them early on.
Just like whitespace, replace the `/` with an underscore
N/A
No, that function is not currently tested.
=> Exclude "/" from pipeline names too as it causes problems in URLs

modules/Bio/EnsEMBL/Hive/GuestProcess.pm, modules/Bio/EnsEMBL/Hive/Scripts/StandaloneJob.pm, modules/Bio/EnsEMBL/Hive/Worker.pm, t/05.runnabledb/java.t, wrappers/java/src/main/java/org/ensembl/hive/TestRunnable.java
I found his bug when testing #104 
```standaloneJob.pl org.ensembl.hive.longmult.DigitFactory -language java -a_multiplier 1234 -b_multiplier 4567 -debug 1```
doesn't work unless you have manually compiled the Java code. The compilation only happens automatically when running init_pipeline.pl or runWorker.pl
I'm making standaloneJob even closer to runWorker by asking the Worker itself to compile the module (after creating a Role that links the Worker to the Analysis), like in the other parts of eHive.
N/A
I will add a test soon
=> standaloneJob for guest-languages

modules/Bio/EnsEMBL/Hive/Worker.pm, t/05.runnabledb/java.t
=> readability fixes

modules/Bio/EnsEMBL/Hive/PipeConfig/HiveGeneric_conf.pm, modules/Bio/EnsEMBL/Hive/Scripts/InitPipeline.pm, modules/Bio/EnsEMBL/Hive/Utils/URL.pm, t/10.pipeconfig/TestPipeConfig/PipelineURL_conf.pm, t/10.pipeconfig/pipeline_url.t
@JAlvarezJarreta and @carlacummins  found an issue in one of the Compara pipelines this morning.
The pipeline defines a SystemCmd with the pipeline's URL, calling `$self->pipeline_url()` (see https://github.com/Ensembl/ensembl-compara/blob/release/97/modules/Bio/EnsEMBL/Compara/PipeConfig/Synteny_conf.pm#L139). When the pipeline is initialized by explictly giving `-pipeline_url`, the URL ends up being wrapped in quotes. It is thus not a valid URL any more.
```
$ init_pipeline.pl Bio::EnsEMBL::Compara::PipeConfig::EBI::Plants::Synteny_conf -pipeline_url 'mysql://ensadmin:xxxxx@mysql-ens-compara-prod-1.ebi.ac.uk:4485/muffato_plants_synteny_98'
$ tweak_pipeline.pl -url mysql://ensro@mysql-ens-compara-prod-1.ebi.ac.uk:4485/muffato_plants_synteny_98 -tweak 'analysis[1].param[cmd]?' …
```
=> pipeline_url quoting

wrappers/java/pom.xml
See https://github.com/Ensembl/ensembl-hive/network/alert/wrappers/java/pom.xml/com.fasterxml.jackson.core:jackson-databind/open and https://nvd.nist.gov/vuln/detail/CVE-2019-12814 for a description of the vulnerability.
I'm not aware of anyone using Java and eHive (I'm only aware of plans to do so) but I thought. Let's patch this and make GitHub happy.
Just bumped to 2.9.9.1. I don't want to define to an open interval as this is version/2.5, which shouldn't get any significant changes, and upstream may break the interface in a 3.* version.
2.9.9.1 seems compatible, so I can't see any drawbacks
Nothing to change.
Yes. OK
=> com.fasterxml.jackson.core 2.9.9 has a vulnerability

wrappers/java/pom.xml
See:
- https://github.com/Ensembl/ensembl-hive/network/alert/wrappers/java/pom.xml/com.fasterxml.jackson.core:jackson-databind/open
- https://nvd.nist.gov/vuln/detail/CVE-2019-14379
- https://nvd.nist.gov/vuln/detail/CVE-2019-14439
Follow-up of #131. There could be more vulnerabilities, so I'm switching to an open interval to pick up the latest 2.9.9.* version
_If applicable, describe any possible undesirable consequence of the changes._
Nothing to change.
Yes
=> com.fasterxml.jackson.core 2.9.9.1 has a vulnerability

scripts/dev/simple_init.py
When running an eHive docker container it will print "ripped a child" when exiting. This was meant to be a debug statement, mistakenly uncommented during #130 
None
N/A
Yes
=> This should have stayed commented out

wrappers/java/pom.xml
At the moment beekeeper will report that the Java wrapper has an incompatible version.
The implementation is already compatible with the 4.* interface, but I forgot to change the version number in pom.xml in #110 / #111 
None
No
Yes
=> bugfix: this needs to match the source code

.travis.yml
Perl 5.14 not being available on Travis @ xenial, Ensembl as a whole is considering a bump of the minimal version (@s-mm brought this up to the ops meeting). All the teams have to start testing on the latest Perl, which is 5.30
Just bumped the version in .travis.yml
None
N/A
Yes
=> Test using the latest Perl on Travis

.travis.yml
The Java tests are currently run twice: in `before_install` and in `scripts/dev/travis_run_tests.sh`. This causes two issues:
- extra Travis time, which is really precious and should not be wasted
- The test build will immediately fail and only report the Java error. There could be other errors worth being reported part of the build
Only run the tests in `scripts/dev/travis_run_tests.sh` (like all the other tests).
Extra Travis time when the only issue is that the Java wrapper doesn't pass its own tests. But the same could be said of any components. It would make sense to test (and fail early) the critical components, but I don't think the Java wrapper is currently critical.
N/A
_Have you run the entire test suite and no regression …
=> [GuestLanguage/java] Don't run the tests in the before_install section as they are run by scripts/dev/travis_run_tests.sh

.travis.yml, modules/Bio/EnsEMBL/Hive/Utils/Test.pm, scripts/dev/travis_run_tests.sh
Some recent Travis builds on `version/2.5` seem to have been stopped because of the inability of downloading maven packages. The hope is that by caching those, the packages won't have to be downloaded and the builds will be faster too.
I have backported the commits made on `master` about the Travis build. I have added a few more commits to tidy up the configuration of Travis
This branch can't be straightforwardly merged into `master`, _git_ reports conflicts 
N/A
N/A
=> Various Travis improvements

modules/Bio/EnsEMBL/Hive/Utils/Graph.pm, modules/Bio/EnsEMBL/Hive/Utils/GraphViz.pm
@JAlvarezJarreta complained that guiHive was unable to display his pipeline. We found that this was caused by the database name having a dot in it. `generate_graph.pl` also fails.
He found the issue on master. Here is the fix for version 2.4, which I will have to merge and adapt to the later branches, but there *will* be some conflicts as this part of the code has changed.
My fix is to quote the _subgraph_ names and remove dots from internal node names (I couldn't find how to quote these, and anyway this is only the internal name - the label works fine).
None
No. There are no tests for generate_graph.pl on 2.4 . These were added on 2.5 only.
I seem to recall that the 2.4 graph generation cannot be reliably configured from the test …
=> bugfix: allow generating graphs of pipelines with a dot in their name

modules/Bio/EnsEMBL/Hive/DBSQL/DBAdaptor.pm, modules/Bio/EnsEMBL/Hive/Process.pm, modules/Bio/EnsEMBL/Hive/URLFactory.pm, modules/Bio/EnsEMBL/Hive/Utils/Config.pm
Carla noticed that the error message she gets when doing `complete_early` includes `at /path/to/Hive/Process.pm line 638`. That's because her message was not ending with `\n`.
I think the module and line numbers are not useful. The purpose of `die` is to break out of the current `eval` and what matters is the user's message.
Similarly, I have changed a few `warn` statements to hide the location.
Just added `\n` where / when needed
Do people find this information useful ?
No
Yes
=> Line returns in die/warn statements

.travis.yml, modules/Bio/EnsEMBL/Hive/DBSQL/DBAdaptor.pm, t/01.utils/dba_dbc.t, t/01.utils/go_figure_dbc.t
When a worker or beekeeper is invoked with a wrong reg_conf argument, there is no explicit warning / error message, only potentially an error about the reg_alias not being found in the Registry.
`Registry::load_all` already has a flag to require the file to exist. I merely enable it and we now get a much clearer error message.
This is a breaking change for people who use a url _and_ an invalid reg_conf at the same time. Previously, there would have been no warnings about the invalid reg_conf, and the database would have been connected to via its URL. Now eHive is going to complain about the reg_conf,
Yes, but requires Ensembl/ensembl#408
Yes
_Have you run the entire test suite and no regression was …
=> Throw if the requested registry file doesn't exist

t/04.meadow/lsf.t
=> [ENSCORESW-3350] update expected output in lsf.t

modules/Bio/EnsEMBL/Hive/Utils/Test.pm
When writing unit-tests for Runnables, it is useful to see the exact events generated by the Runnable in order to copy-paste them. It also helps spotting the differences between what's expected and what's generated without having to bring `Test::Differences` in
I added several calls to `diag`
None
We don't have unit-tests for the test interface, but I've used the new functionality to write new unit-tests for Compara
All good
=> Test interface: show the content of the events with diag

.codecov.yml
I personally find the codecov messages too invasive. Unlike coveralls, they cannot be controlled from the codecov website, it has to be set in `codecov.yml`
This is not my first attempt. I hope this one will work ! We'll quickly see on this PR
I change `codecov.yml` to disable the comments. codecov should still notify if the coverage drops by more than 1%. I could test this by doing a fake PR that removes most of the test suite.
Code coverage stats will be less visible
This PR will test things live
=> Silence codecov

modules/Bio/EnsEMBL/Hive/Utils/URL.pm, t/01.utils/url.t, t/02.api/create_drop_database.t, t/03.scripts/beekeeper_opts.t, t/03.scripts/beekeeper_reset.t
My motivation was to make the output of `prove -r t` clearer by removing spurious eHive messages. 
I'm achieving that by capturing stdout/stderr accordingly and checking that they are as expected. I also check that eHive issues warnings as expected (e.g. URL parsing)
When changing some error messages we'll have to change the unit-test as well.
There are still some tests that will have stuff printed to stderr and that I haven't been able to silence / test yet.
Yes
Yes
Yes
=> Misc. changes re. testing the text outputs

modules/Bio/EnsEMBL/Hive/RunnableDB/DatabaseDumper.pm
This bug is not causing any errors, but Perl is issuing some warnings ("unitialized value in lt", "unitialized value in sprintf") in standaloneJob context. I'd like to avoid those warnings.
The dbID used to be -1 in standaloneJob context on version/2.4, but was changed to _undef_ on version/2.5. This Runnable should have been updated at the same time.
None
No
Yes
=> bugfix: dbID is not set to -1 in standaloneJob any more

modules/Bio/EnsEMBL/Hive/DBSQL/AnalysisJobAdaptor.pm, t/03.scripts/beekeeper_reset.t
There has been some transient Travis failures recently, and they seem to arise from `t/03.scripts/beekeeper_reset.t`. The problem is that runWorker doesn't always run the jobs in the same order, so the job statuses don't match what the test expects.
See https://travis-ci.org/Ensembl/ensembl-hive/jobs/614039653 and https://travis-ci.org/Ensembl/ensembl-hive/jobs/613529841
Instead of running a single generic runWorker command, run specific jobs in a certain order.
At the same time, I simplify the AnalysisJob adaptor a little bit, as we don't need to always CAST the job status in PostreSQL. It is only needed for CASE expressions, as they otherwise default to a being a string.
None
Yes
Yes
_Have you run …
=> Misc. changes re. PostgreSQL

wrappers/java/src/main/java/org/ensembl/hive/RunWrapper.java, wrappers/java/wrapper
When reinstalling my laptop I realised that none of the Java versions compatible with eHive (i.e. 12+) are LTS, and it won't be the case for another 18 months, see https://en.wikipedia.org/wiki/Java_version_history
The problem comes from using a package named `SharedSecrets` which provides a way of referring to a file descriptor by integer (such integers can't otherwise be set in Java). The package has had multiple names through time
- `sun.misc.SharedSecrets` in Oracle JDK 8
- `jdk.internal.misc.SharedSecrets` in OpenJDK <12
- `jdk.internal.access.SharedSecrets` in OpenJDK 12+
In #104 #109 #111 we decided with @mira13 to use the most recent denomination, but I didn't realise there wouldn't be any LTS release covering it.
I have found another hack. Using reflection, we can find the …
=> Don't use SharedSecrets, but instead directly call a private constructor

modules/Bio/EnsEMBL/Hive/RunnableDB/SystemCmd.pm
I've found cases where the process was being killed by LSF (MEMLIMIT) but there was also an exit code in the upper 8 bits. In those cases, we still want to go through the MEMLIMIT path.
I changed the condition from "not having data in the upper 8 bits) to "having data in lower 8 bits".
Note that because this module has frequently changed, it won't be a straightforward merge. The equivalent commits are:
- [version 2.4](https://github.com/Ensembl/ensembl-hive/commit/390909d31c7821f0d08e6016990a4778b983a83a)
- [version 2.5](https://github.com/Ensembl/ensembl-hive/commit/f86a618117276227c183a5298a3251ffa54c7530)
None envisaged
Not sure how to test this. Most of the time a kill results in only the lower 8 bits having some data
_Have you …
=> Better detection of the process being killed

modules/Bio/EnsEMBL/Hive/Queen.pm
Found two issues when calling beekeeper with `-big_red_button`.
1. beekeeper tried to kill workers of another user
2. beekeeper didn't clean up the temporary directories
Both issues are quite straightforward to fix
None envisaged
1. Can't have more than 1 user in the test-suite.
2. About the temp directory, I would have to change the `longrunning` analysis of the example pipeline `LongWorker` to make it write somewhere. Can I do that ? \
By the way, this example pipeline is only referenced in the test-suite (introduced in b98c8b891df5d962934fc4b711b893170ff56727) and I don't think it has any pedagogical value (unlike `CompressFiles`, `MemlimitTest`, etc). Would you mind if I move it to `t/10.pipeconfig/TestPipeConfig` and change …
=> Improved big red button

wrappers/python3/eHive/Process.py, wrappers/python3/wrapper
Two bugs I have found when working on the Python codebase. The wrapper has changed a little bit, and I believe there will be a conflict when merging into 2.5, meaning this has to be done manually and bypass the branch protection
1. The `autoflow` attribute was used on the wrong object
2. Wrong number of arguments when calling `usage`
NA
No test updated / written. I can add some if you want. For the dataflow thing, I would have to write a new Python runnable that dataflows its own stuff onto branch #1. The wrapper has no unit-test yet
=> Python bugfixes

t/05.runnabledb/dummy.t
When running on Travis, `sleep(10)` may sleep for less than 10 seconds.
We have no explanation for this, so when it happens we simply restart the
job.
```
```
`dummy.t` detects it is running on Travis and expects that 9 seconds have
elapsed instead of 10. I think all the cases we have seen are > 9.5 seconds
so we should avoid most failures.
Note that I have also removed the estimation of the overhead. I (now) think
it is not needed in this Runnable. All that matters is that we slept
enough.
None
Yes
Yes
Yes
=> Account for time slippage on Travis

modules/Bio/EnsEMBL/Hive/DBSQL/BaseAdaptor.pm
If you use a tweak that changes dataflows / wait_for rules when initialising the pipeline, e.g.
```
init_pipeline.pl Bio::EnsEMBL::Hive::Examples::LongMult::PipeConfig::LongMult_conf -pipeline_url $URL -tweak 'analysis[take_b_apart].flow_into=["part_multiply"]'
```
you will see this Perl warning
```
Use of uninitialized value in concatenation (.) or string at /home/matthieu/workspace/src/hive/2.4/modules/Bio/EnsEMBL/Hive/DBSQL/BaseAdaptor.pm line 387.
```
This is because when the pipeline is tweaked, it only exists in memory, not in the database, and the `flow_into` update works by 1) removing the previous dataflow targets and 2) adding the new ones. The previous targets not being stored, a warning is shown.
The fix is to return early in the `remove` method when the object hasn't been …
=> Don't attempt removing objects that haven't been stored

modules/Bio/EnsEMBL/Hive/Utils/PCL.pm, t/02.api/pipeconfig_parser.t
`init_pipeline` accepts invalid URLs (e.g. URLs that can't be parse), meaning that the problem is revealed much later (when drawing the diagram or when the actual dataflow happens)
@CristiGuijarro was affected by this. In the PipeConfig she had something like
```
flow_into => [ 'a' => INPUT_PLUS() ],
```
i.e. an array-ref instead of an hash-ref. `init_pipeline` didn't complain and stored a dataflow rule on branch 1 for the target named `+` (which is the internal string to indicate `INPUT_PLUS`).
With this change, `init_pipeline` will check that the URLs are valid and die if they're not. The change being in Utils::PCL, `generate_graph.pl -pipeconfig` will benefit from it too.
None
Yes. Note that the unit-test is directly testing …
=> init_pipeline should check that dataflow targets are valid URLs

docs/quickstart/install.rst
Graphviz 2.40+ doesn't work well with eHive. We should document this.
At the same time, I have found that the installation guide could use more
RST styling options.
Documentation updated.
NA
I have built the doc locally and checked that it looks fine.
=> Updated installation guide (esp. re. Graphviz)

modules/Bio/EnsEMBL/Hive/Scripts/StandaloneJob.pm
If you add the SLURM meadow to your PERL5LIB, you will notice some of its
debug statements when running stansaloneJob. It's because the constructor
of Valley calls `loaded_meadow_drivers` which lists and loads all the
available Meadow drivers.
I believe that's not necessary. In standaloneJob job the worker is pretty
much a fake one. Its purpose is to mimic the "real" execution of the job
(alongside a fake Role, a fake Analysis, a fake Job, etc) but that's all.
The Worker is not recorded anywhere, and the attributes that are pulled
from the Valley are not used anywhwere.
Anyway, I think standaloneJob shouldn't bother about all the meadows. It
represents a debugging task and as such should just assume to be running on
LOCAL.
The change sets the list of loaded drivers to LOCAL only, so that …
=> In standaloneJob mode there is no need to query all meadows

docs/rtd_upgrade.sh
Supersedes #168 
We currently get the .deb packages by directly downloading them from the Ubuntu repository. This involves finding the version and the actual path via https://packages.ubuntu.com and maintaining the list. We've had to update the URLs several times as the ReadTheDocs builds were broken.
Here I suggest using `apt-get download` to download the packages. It will itself select the right version and download it from the Ubuntu repository.
`apt-get` requires the `apt` cache to be populated (typically `apt-cache update`) but we can't do that as non-root, so we need to hope it's been done, which seems to be the case :)
ReadTheDocs built successfully: https://readthedocs.org/projects/ensembl-hive/builds/11386178/
=> Use `apt` to download the packages

scripts/dev/travis_run_tests.sh, wrappers/python3/README.md, wrappers/python3/eHive/__init__.py, wrappers/python3/eHive/params.py, wrappers/python3/eHive/process.py
As Ensembl is doing more Python there will be more scrutiny on eHive's Python wrapper. `pylint` is a popular Python linter. It complains quite a lot about our code :see_no_evil: as we are not following Python's best practices
I'm not (yet) keen on addressing every complain, especially as it would change the file history and make it more difficult to trace back the origin of the implementation. However, I think that some changes should still be made in order not to be too far away from the Python world.
I have applied these changes:
- the eHive internal modules are all named in lower case. I haven't changed the main package name `eHive` and the example runnables because that would be a breaking change.
- All internal modules have a dosctring at the beginning
- I broke down the `__all__` …
=> Cleaner Python code

modules/Bio/EnsEMBL/Hive/RunnableDB/DatabaseDumper.pm
A few changes to improve maintainability of `RunnableDB::DatabaseDumper`
1. Instead of setting the command to `true` to breeze through `run` and `write_output`, use `$self->complete_early()` (which was introduced after the creation of this Runnable
2. Don't add the "signature" if the Runnable is run in standalone mode,
None envisaged
There are no tests for this Runnable
=> Code maintenance - RunnableDB::DatabaseDumper

scripts/generate_timeline.pl
In Gnuplot's enhanced mode (which powers `generate_timeline.pl`), the string "a_b" is displayed as "a" followed by "b" in subscript. Most of our analyses use underscore, so the names are quite messed up.
The fix is simply to disable the enhanced mode.
Note
For `ps` and `pdf` formats, the instruction "color" has been renamed to "colour" in a later version of eHive. That will conflict when you do the merge.
There is no unit-test for generate_timeline, but here is how the changes look:
(the diagrams were generated on different databases, hence the different ordering of the analyses)
=> Don't use the enhanced mode as it messes up most analysis names

modules/Bio/EnsEMBL/Hive/Meadow/LSF.pm, t/04.meadow/fake_bin/lsid, t/04.meadow/lsf.t, t/04.meadow/lsf_detection/no_slurm_gcloud/lsid, t/04.meadow/lsf_detection/ok_EBI/lsid, t/04.meadow/lsf_detection/ok_YODA/lsid, t/04.meadow/lsf_detection/ok_cluster1/lsid, t/04.meadow/lsf_detection/ok_lsf91_bw3/lsid, t/04.meadow/lsf_detection/ok_openlava/lsid
We are testing some pipelines in a Slurm farm that provides `lsid`, and eHive activates the LSF meadow tries to submit jobs with `bsub` etc, which doesn't exist, and fails.
A workaround is to run beekeeper with `--meadow_type SLURM`, but I believe the LSF meadow should be fixed.
Slurm's `lsid` does print it is a Slurm, it doesn't pretend to be an LSF. The fix is change the parsing of `lsid` to look for the LSF keyword, and openlava too since they are mostly the same.
None envisaged.
Yes, `lsf.t` now tests the meadow detection against a collection of `lsid` outputs
They do
All good (but remember that we don't have Travis any more !)
=> Bugfix LSF detection

t/04.meadow/lsf_detection/ok_lsf91_bw3/lsid, t/apache2.t, t/ascii.t
=> Fix apache2.t and ascii.t failures

README.md
=> Update README.md to reflect end of maintainence

scripts/dev/generate_timeline_example_key_transform_file.pl, scripts/generate_timeline.pl
James asked us to extract farm usage statistics for the migration to Codon, for some memory classes. I have used `generate_timeline.pl` to get the data for Compara, but did a few changes to allow defining the custom classes he wanted to have (which in our cases consisted of grouping some of our resource classes together).
`generate_timeline.pl` accepts a new parameter: a script that defines a function named `get_key_name` that, given an Analysis or a ResourceClass object, returns a category name for this object. Objects that have the same category name are grouped together and displayed with the name given. I have added the function that I used for Compara as an example.
I also took the opportunity to rename several variables for clarity.
None
_Have you added/modified unit tests to test …
=> [generate_timeline] Define custom categories to group analyses / resource-classes

wrappers/python3/wrapper
More changes I should have put into #166 . They make `wrappers/python3/wrapper` more compliant with `pylint` (although still not 100%) and more Pythonic.
The biggest change is to use a `namedtuple` to hold the details about each mode of the wrapper instead of a regular tuple. This means that the data can be accessed through named properties `function` and `args` rather than indices `[0]` and `[1]`.
None
The wrapper is covered by several tests
=> Cleaner python wrapper

modules/Bio/EnsEMBL/Hive/PipeConfig/EnsemblGeneric_conf.pm
EnsemblGeneric_conf checks for installed Ensembl modules in $ENSEMBL_CVS_ROOT_DIR, but these modules will be stored in $ENSEMBL_ROOT_DIR on Codon. This change ensures that we check both directories, with the following priorities in place:
- 'ensembl_root_dir' passed on the command line
- 'ensembl_cvs_root_dir' passed on the command line
- $ENSEMBL_ROOT_DIR environment variable
- $ENSEMBL_CVS_ROOT_DIR environment variable
JIRA ticket: https://www.ebi.ac.uk/panda/jira/browse/ENSCORESW-3735
This fix gives values passed through the command line priority over environment variables, but it was the reverse before. Thus, this fix changes the behavior of the code so users should be aware of that. However, the reverse of this was deemed a bug and users have asked for this fix so all should be good. …
=> Checks for ENSEMBL_ROOT_DIR and ENSEMBL_CSV_ROOT_DIR

modules/Bio/EnsEMBL/Hive/PipeConfig/EnsemblGeneric_conf.pm
=> rework setting of ensembl_cvs_root_dir in response to user bug report

modules/Bio/EnsEMBL/Hive/Meadow/LSF.pm, t/04.meadow/lsf.t
=> update bacct command line for codon compatibility [ENSCORESW-3805]

hive_config.json, modules/Bio/EnsEMBL/Hive/Meadow/LSF.pm, t/04.meadow/lsf.t
=> Making bacct options configurable according to cluster

scripts/dev/travis_run_tests.sh
=> ignore failures in coverage testing

scripts/beekeeper.pl
When running beekeeper in -loop mode, the pipeline name is only displayed at the start. For users who run multiple pipelines at the same time, it can be confusing as to what pipeline a specific beekeeper is looping for, especially if it has been running for a while and has gone through many loops. This feature helps with that by displaying the pipeline name and url at every iteration.
Adding the current pipeline name and url at the start of every beekeeper loop.
None
No
=> Display pipeline name and url at each iteration

.travis.yml, modules/Bio/EnsEMBL/Hive/Accumulator.pm, t/10.pipeconfig/TestPipeConfig/Accumulator/NullHashKey_conf.pm, t/10.pipeconfig/accumulator.t
When hash key is set to null in dataflow
When hashkey is set to null, next job fails to read it, but it should be that current job fails to read it
Not found
Yes
=> Revisited 'Drop error on null hash key in accu , PR #177'

modules/Bio/EnsEMBL/Hive/Meadow/SLURM.pm
Remove a redundant message in the Slurm meadow that is already printed by beekeeper.
=> Remove redundant message

modules/Bio/EnsEMBL/Hive/PipeConfig/EnsemblGeneric_conf.pm, modules/Bio/EnsEMBL/Hive/PipeConfig/HiveGeneric_conf.pm
Part of the instructions for Ensembl in our move to Codon were to start using `ENSEMBL_ROOT_DIR`, so whilst support for the previous variable should remain, I believe having this can be useful in eHive as well. Furthermore, `yesterday` queue is something of the past (Noah), and I guess the most adequate replacement would be `production`.
None.
This code has been used by Compara and part of Metazoa for several releases without issues.
Merging these into `main` branch would be nice as well :)
=> Tiny tweaks related to migration to Codon

cpanfile, pyproject.toml
DBD::mysql have released new version (5.001) on Oct 4, 2023. This version removes support for MySQL 5 -
https://metacpan.org/dist/DBD-mysql/changes
Hence we need to use lower version than that.
Using DBAdaptors to connect to Ensembl databases which use MySQL version 5
Should be changed back if anytime in the future Ensembl database servers upgraded to MySQL 8x.
Unit test should pass on this PR
=> Restrain using DBD::mysql version 5.x

.readthedocs.yml
Somehow, the build file for RTD was not picked up when merging the branches.
This should fix the build.
=> Update readthedocs build

modules/Bio/EnsEMBL/Hive/Meadow/SLURM.pm
Check for undefined config hash before setting config.
Some teams instantiate a Valley without config to query which Meadows are available.
=> Check for undefined config hash

docs/requirements.txt
- readthedocs no longer installs some dependencies. Add them explicitly.
They also mention mock, pillow and commonmark, but I believe we do not need those.
=> Add recommonmark for rtd

README.md, docs/contrib/alternative_meadows.rst, docs/creating_pipelines/meadows_and_resources.rst, docs/creating_pipelines/pipeconfigs.rst, docs/dev/development_guidelines.rst, docs/running_pipelines/error-recovery.rst, docs/running_pipelines/management.rst
We have deprecated eHive support for some job scheduler, and consequently eHive meadows.
Docs need updating to reflect these changes.
None
N/A
=> Updated docs because of meadow deprecations

docs/appendix/changelog.rst, modules/Bio/EnsEMBL/Hive/Meadow/SLURM.pm, modules/Bio/EnsEMBL/Hive/Version.pm
- sinfo does not print the slurmd version for each partition, instead giving N/A. We now run 'sinfo -V' separately to get the version.
=> Adapt to changes in sinfo output
