modules/Bio/EnsEMBL/Hive/Utils/PCL.pm
This has already been fixed on master (via 5a40ea190) and I'm backporting it to 2.4
=> bugfix: the / is a remnant of the previous regex

modules/Bio/EnsEMBL/Hive/DBSQL/StatementHandle.pm, t/02.api/reconnect.t
See #41 for the purpose of the change
This is an alternative implementation.
=> Expose DBI::st's hash interface through StatementHandle

scripts/generate_timeline.pl
Here are a few changes I have locally
=> Matthieu/misc 2.5

docs/dev/development_guidelines.rst
Adding a note about how PRs are handled, including a reminder about how to merge the PR in GitHub
=> documentation update - more detail on handling pull requests

.travis.yml, docs/eHive_install_usage.txt, docs/install.html
I've updated the docs and .travis.yml
I've also enabled testing on Perl 5.26, which we didn't test before. Fingers crossed it won't reveal any bug !
=> End of support for older Perl versions

PULL_REQUEST_TEMPLATE.md
This template is based on the one used by many of the core Ensembl repos. With the increasing number of contributors, perhaps it's time to introduce one?
=> add a pull request template

modules/Bio/EnsEMBL/Hive/Queen.pm
=> bugfix: without $self this is a function call, not a method call

t/02.api/latest_schema_patch.t
The daily Travis builds have been failing on PostgreSQL for a few days. This is because of a change in `DBD::Pg` version 3.8.0 released a few days ago: https://metacpan.org/changes/distribution/DBD-Pg (commits https://github.com/bucardo/dbdpg/commit/527fd30d2335b15d1d023dc52e1dae0b1deb71ec and https://github.com/bucardo/dbdpg/commit/a86442432e3a4322aa3ad04d3cdca6aa44a67927 )
The column_info structure now includes the database name in the `TABLE_CAT` field (instead of _undef_ before). Since the test creates two different databases (`travis_ehive_test_old_patched` vs `travis_ehive_test_new`) on the same server and compares their schema, it is now failing.
Just discard the `TABLE_CAT` field from the comparison
None envisaged
Not …
=> bugfix: Since version 3.8.0 DBD::Pg returns the database name in TABLE_CAT

modules/Bio/EnsEMBL/Hive/GuestProcess.pm, modules/Bio/EnsEMBL/Hive/Scripts/StandaloneJob.pm, modules/Bio/EnsEMBL/Hive/Worker.pm, t/05.runnabledb/java.t, wrappers/java/src/main/java/org/ensembl/hive/TestRunnable.java
=> Merge standaloneJob for guest languages into master

modules/Bio/EnsEMBL/Hive/GuestProcess.pm, modules/Bio/EnsEMBL/Hive/PipeConfig/HiveGeneric_conf.pm, modules/Bio/EnsEMBL/Hive/Scripts/InitPipeline.pm, modules/Bio/EnsEMBL/Hive/Scripts/StandaloneJob.pm, modules/Bio/EnsEMBL/Hive/Utils/URL.pm, modules/Bio/EnsEMBL/Hive/Worker.pm, t/05.runnabledb/java.t, t/10.pipeconfig/TestPipeConfig/PipelineURL_conf.pm, t/10.pipeconfig/pipeline_url.t, wrappers/java/src/main/java/org/ensembl/hive/TestRunnable.java
=> Merge pipeline url quoting into master

scripts/dev/simple_init.py
(reported by @tweep on the eHive-users mailing-list)
When running an eHive command through Docker, the container returns the exit code 0 even if there are some errors.
```
$ docker run -it ensemblorg/ensembl-hive seed_pipeline.pl --url mysql://user@blst.abc
Use of uninitialized value in concatenation (.) or string at /repo/ensembl-hive/modules/Bio/EnsEMBL/Hive/DBSQL/CoreDBConnection.pm line 324.
Could not connect to database  as user user using [DBI:mysql:host=blst.abc;port=3306] as a locator:
DBI connect('host=blst.abc;port=3306','user',...) failed: Unknown MySQL server host 'blst.abc' (0) at /repo/ensembl-hive/modules/Bio/EnsEMBL/Hive/DBSQL/CoreDBConnection.pm line 317.
Use of uninitialized value in concatenation (.) or string at …
```
=> bugfix: "returncode" is never set, so get the exit status from `waitpid`

scripts/dev/simple_init.py, wrappers/java/pom.xml
=> cascade merge of Docker return code and com.fasterxml.jackson.core fixes from 2.5 into master

scripts/dev/simple_init.py, wrappers/java/pom.xml
=> Cascade merge of PRs #134 and #135 into master

modules/Bio/EnsEMBL/Hive/HivePipeline.pm
I was running some tests and had to use Data::Dumper on a HivePipeline object, and saw all those strings defined in the object itself. It just doesn't feel right. Those strings are set for the class and won't change between instances.
I can't remember if we discussed this in the pull-request #62 where those have been introduced, and sorry if I've changed my mind about this.
I move the strings out of the object, and put them as "constants" at the package level.
None
Not needed, there is already a comprehensive test for the JSON writer
After rebasing onto the copyright change: all good
=> These should be class-wide attributes, not per instance

modules/Bio/EnsEMBL/Hive/DBSQL/AnalysisJobAdaptor.pm
I want to fix this error:
```
$ beekeeper.pl -url $URL -reset_failed_jobs -analyses_pattern create_alignment_nets_jobs
Pipeline name: vertebrates_lastz_batch1_100
Default meadow: LSF/EBI
Beekeeper : the following Analyses matched your -analyses_pattern 'create_alignment_nets_jobs' : create_alignment_nets_jobs(25)
Beekeeper : 41 Analyses are not shown
DBD::mysql::db do failed: Lock wait timeout exceeded; try restarting transaction at /homes/muffato/workspace/src/hive/master/modules/Bio/EnsEMBL/Hive/DBSQL/CoreDBConnection.pm line 988.
ABORT: Transaction aborted because of error: DBD::mysql::db do failed: Lock wait timeout exceeded; try restarting transaction at /homes/muffato/workspace/src/hive/master/modules/Bio/EnsEMBL/Hive/DBSQL/CoreDBConnection.pm line 988.
at …
```
=> Added deadlock protection to these operations

t/03.scripts/TestPipeConfig/LongWorker_conf.pm, t/03.scripts/TestRunnable/DummyWriter.pm, t/03.scripts/beekeeper_big_red_button.json, t/03.scripts/beekeeper_big_red_button.t, t/03.scripts/beekeeper_opts.t
Follow-up of #156 . I pressed _Merge_ too quickly and forgot to add the unit test.
I have moved the `LongWorker` example pipeline to the test-suite because there is nothing to learn from it. I have expanded the "big red button" test to test the deletion of the temp directory (I think that Meadow method was not yet tested, so the test coverage should slightly increase :crossed_fingers: )
Anyone in deed of this PipeConfig won't be able to access it any more
Yes
Yes
Yes
=> Moved the pipeline to the test-suite since it is only useful there

wrappers/python3/eHive/Params.py, wrappers/python3/eHive/examples/TestRunnable.py
Same PR as https://github.com/Ensembl/ensembl-hive/pull/171 but against 2.4.
=> One hash fix 2.4

docs/index.rst, docs/quickstart/tips.rst
No requirements
Beginners start to use eHive and looking for additional info
Tips added to documentation for optimised usage of eHive
https://www.ebi.ac.uk/panda/jira/browse/ENSCORESW-2437
no
No testing aplicable.
=> Tips included in documentation.

scripts/dev/generate_timeline_example_key_transform_file.pl
=> add license to generate_timeline_example_key_transform_file.pl

modules/Bio/EnsEMBL/Hive/DataflowRule.pm, modules/Bio/EnsEMBL/Hive/ResourceClass.pm, modules/Bio/EnsEMBL/Hive/ResourceDescription.pm, sql/procedures.mysql, sql/procedures.pgsql, sql/procedures.sqlite
Various documentation updates I have found and not yet fixed. I'll leave this PR as a draft until I finish going through all my local dev branches.
None
N/A
=> Misc. documentation update

modules/Bio/EnsEMBL/Hive/HivePipeline.pm, t/03.scripts/tweak_pipeline_output.t
Equivalent of #183 but for the `master` branch. This time I have added a test in `tweak_pipeline_output.t`. Remember that the latter only checks that the output JSON conforms to the spec, not that each individual tweak is doing the correct thing (for that you need to run the test in verbose mode and read its output)
None
Yes
=> Various bug fixes in tweak_pipeline

docs/appendix/changelog.rst
=> update changelog for version/2.6

modules/Bio/EnsEMBL/Hive/Meadow/SLURM.pm
Integrate basic support for Slurm into eHive
=> Add Slurm support

docs/conf.py, docs/requirements.txt
- sphinx_rtd_theme must now be installed separately
=> Update read the docs config

Changes, docs/appendix/changelog.rst
=> Update changelogs for 2.7.0

docs/rtd_upgrade.sh, modules/Bio/EnsEMBL/Hive/Version.pm
- The main branch is now 2.7.1
- Point to 2.7.0 for the RTD build
=> Increment version

docs/appendix/changelog.rst, modules/Bio/EnsEMBL/Hive/Meadow/SLURM.pm, modules/Bio/EnsEMBL/Hive/Version.pm
This version fixes an incompatibility with the Slurm 24 sinfo command.
=> Merge bugfix from main
